In [4]:

from numpy import array
from keras.models import Sequential, Model
from keras.layers import Dense
from keras.layers import LSTM
# prepare sequence
length = 5
seq = array([i/float(length) for i in range(length)])
X = seq.reshape(len(seq), 1, 1)
y = seq.reshape(len(seq), 1)
# define LSTM configuration
n_neurons = length
n_batch = length
n_epoch = 1000
# create LSTM
model = Sequential()
model.add(LSTM(n_neurons, input_shape=(1, 1)))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')
print(model.summary())
# train LSTM
model.fit(X, y, epochs=n_epoch, batch_size=n_batch, verbose=2)
# evaluate
result = model.predict(X, batch_size=n_batch, verbose=0)
for value in result:
	print('%.1f' % value)

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_3 (LSTM)                (None, 5)                 140       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 6         
Total params: 146
Trainable params: 146
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/1000
 - 0s - loss: 0.2899
Epoch 2/1000
 - 0s - loss: 0.2881
Epoch 3/1000
 - 0s - loss: 0.2862
Epoch 4/1000
 - 0s - loss: 0.2844
Epoch 5/1000
 - 0s - loss: 0.2826
Epoch 6/1000
 - 0s - loss: 0.2808
Epoch 7/1000
 - 0s - loss: 0.2790
Epoch 8/1000
 - 0s - loss: 0.2773
Epoch 9/1000
 - 0s - loss: 0.2755
Epoch 10/1000
 - 0s - loss: 0.2738
Epoch 11/1000
 - 0s - loss: 0.2721
Epoch 12/1000
 - 0s - loss: 0.2704
Epoch 13/1000
 - 0s - loss: 0.2687
Epoch 14/1000
 - 0s - loss: 0.2670
Epoch 15/1000
 - 0s - loss: 0.26

 - 0s - loss: 0.0694
Epoch 215/1000
 - 0s - loss: 0.0690
Epoch 216/1000
 - 0s - loss: 0.0686
Epoch 217/1000
 - 0s - loss: 0.0683
Epoch 218/1000
 - 0s - loss: 0.0679
Epoch 219/1000
 - 0s - loss: 0.0675
Epoch 220/1000
 - 0s - loss: 0.0672
Epoch 221/1000
 - 0s - loss: 0.0668
Epoch 222/1000
 - 0s - loss: 0.0665
Epoch 223/1000
 - 0s - loss: 0.0661
Epoch 224/1000
 - 0s - loss: 0.0658
Epoch 225/1000
 - 0s - loss: 0.0654
Epoch 226/1000
 - 0s - loss: 0.0651
Epoch 227/1000
 - 0s - loss: 0.0648
Epoch 228/1000
 - 0s - loss: 0.0645
Epoch 229/1000
 - 0s - loss: 0.0642
Epoch 230/1000
 - 0s - loss: 0.0639
Epoch 231/1000
 - 0s - loss: 0.0636
Epoch 232/1000
 - 0s - loss: 0.0633
Epoch 233/1000
 - 0s - loss: 0.0630
Epoch 234/1000
 - 0s - loss: 0.0627
Epoch 235/1000
 - 0s - loss: 0.0624
Epoch 236/1000
 - 0s - loss: 0.0621
Epoch 237/1000
 - 0s - loss: 0.0619
Epoch 238/1000
 - 0s - loss: 0.0616
Epoch 239/1000
 - 0s - loss: 0.0613
Epoch 240/1000
 - 0s - loss: 0.0611
Epoch 241/1000
 - 0s - loss: 0.0608
Epoch 2

Epoch 442/1000
 - 0s - loss: 0.0349
Epoch 443/1000
 - 0s - loss: 0.0347
Epoch 444/1000
 - 0s - loss: 0.0346
Epoch 445/1000
 - 0s - loss: 0.0345
Epoch 446/1000
 - 0s - loss: 0.0344
Epoch 447/1000
 - 0s - loss: 0.0343
Epoch 448/1000
 - 0s - loss: 0.0342
Epoch 449/1000
 - 0s - loss: 0.0341
Epoch 450/1000
 - 0s - loss: 0.0339
Epoch 451/1000
 - 0s - loss: 0.0338
Epoch 452/1000
 - 0s - loss: 0.0337
Epoch 453/1000
 - 0s - loss: 0.0336
Epoch 454/1000
 - 0s - loss: 0.0335
Epoch 455/1000
 - 0s - loss: 0.0334
Epoch 456/1000
 - 0s - loss: 0.0333
Epoch 457/1000
 - 0s - loss: 0.0331
Epoch 458/1000
 - 0s - loss: 0.0330
Epoch 459/1000
 - 0s - loss: 0.0329
Epoch 460/1000
 - 0s - loss: 0.0328
Epoch 461/1000
 - 0s - loss: 0.0327
Epoch 462/1000
 - 0s - loss: 0.0326
Epoch 463/1000
 - 0s - loss: 0.0325
Epoch 464/1000
 - 0s - loss: 0.0323
Epoch 465/1000
 - 0s - loss: 0.0322
Epoch 466/1000
 - 0s - loss: 0.0321
Epoch 467/1000
 - 0s - loss: 0.0320
Epoch 468/1000
 - 0s - loss: 0.0319
Epoch 469/1000
 - 0s - loss:

Epoch 670/1000
 - 0s - loss: 0.0106
Epoch 671/1000
 - 0s - loss: 0.0105
Epoch 672/1000
 - 0s - loss: 0.0104
Epoch 673/1000
 - 0s - loss: 0.0104
Epoch 674/1000
 - 0s - loss: 0.0103
Epoch 675/1000
 - 0s - loss: 0.0102
Epoch 676/1000
 - 0s - loss: 0.0101
Epoch 677/1000
 - 0s - loss: 0.0100
Epoch 678/1000
 - 0s - loss: 0.0100
Epoch 679/1000
 - 0s - loss: 0.0099
Epoch 680/1000
 - 0s - loss: 0.0098
Epoch 681/1000
 - 0s - loss: 0.0097
Epoch 682/1000
 - 0s - loss: 0.0096
Epoch 683/1000
 - 0s - loss: 0.0096
Epoch 684/1000
 - 0s - loss: 0.0095
Epoch 685/1000
 - 0s - loss: 0.0094
Epoch 686/1000
 - 0s - loss: 0.0093
Epoch 687/1000
 - 0s - loss: 0.0092
Epoch 688/1000
 - 0s - loss: 0.0092
Epoch 689/1000
 - 0s - loss: 0.0091
Epoch 690/1000
 - 0s - loss: 0.0090
Epoch 691/1000
 - 0s - loss: 0.0089
Epoch 692/1000
 - 0s - loss: 0.0089
Epoch 693/1000
 - 0s - loss: 0.0088
Epoch 694/1000
 - 0s - loss: 0.0087
Epoch 695/1000
 - 0s - loss: 0.0086
Epoch 696/1000
 - 0s - loss: 0.0086
Epoch 697/1000
 - 0s - loss:

Epoch 897/1000
 - 0s - loss: 8.7041e-04
Epoch 898/1000
 - 0s - loss: 8.5959e-04
Epoch 899/1000
 - 0s - loss: 8.4892e-04
Epoch 900/1000
 - 0s - loss: 8.3840e-04
Epoch 901/1000
 - 0s - loss: 8.2803e-04
Epoch 902/1000
 - 0s - loss: 8.1780e-04
Epoch 903/1000
 - 0s - loss: 8.0773e-04
Epoch 904/1000
 - 0s - loss: 7.9780e-04
Epoch 905/1000
 - 0s - loss: 7.8801e-04
Epoch 906/1000
 - 0s - loss: 7.7836e-04
Epoch 907/1000
 - 0s - loss: 7.6886e-04
Epoch 908/1000
 - 0s - loss: 7.5949e-04
Epoch 909/1000
 - 0s - loss: 7.5025e-04
Epoch 910/1000
 - 0s - loss: 7.4116e-04
Epoch 911/1000
 - 0s - loss: 7.3219e-04
Epoch 912/1000
 - 0s - loss: 7.2336e-04
Epoch 913/1000
 - 0s - loss: 7.1466e-04
Epoch 914/1000
 - 0s - loss: 7.0608e-04
Epoch 915/1000
 - 0s - loss: 6.9763e-04
Epoch 916/1000
 - 0s - loss: 6.8931e-04
Epoch 917/1000
 - 0s - loss: 6.8111e-04
Epoch 918/1000
 - 0s - loss: 6.7304e-04
Epoch 919/1000
 - 0s - loss: 6.6508e-04
Epoch 920/1000
 - 0s - loss: 6.5725e-04
Epoch 921/1000
 - 0s - loss: 6.4953e-04


In [9]:
from numpy import array
from keras.models import Sequential, Model
from keras.layers import Dense, Input
from keras.layers import LSTM

# prepare sequence
length = 5
seq = array([i/float(length) for i in range(length)])
X = seq.reshape(1, length, 1)
y = seq.reshape(1, length)

# define LSTM configuration
n_neurons = length
n_batch = length
n_epoch = 500

# create LSTM
# model = Sequential()
# model.add(LSTM(n_neurons, input_shape=(length, 1)))
# model.add(Dense(length))
# model.compile(loss='mean_squared_error', optimizer='adam')
# print(model.summary())

inputs = Input((length, 1))
lstm = LSTM(n_neurons)(inputs)
dense = Dense(length)(lstm)

model = Model(inputs, dense)
model.compile(loss='mean_squared_error', optimizer='adam')

model.summary()

Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         (None, 5, 1)              0         
_________________________________________________________________
lstm_7 (LSTM)                (None, 5)                 140       
_________________________________________________________________
dense_7 (Dense)              (None, 5)                 30        
Total params: 170
Trainable params: 170
Non-trainable params: 0
_________________________________________________________________


In [10]:
# train LSTM
model.fit(X, y, epochs=n_epoch, batch_size=n_batch, verbose=2)

# evaluate
result = model.predict(X, batch_size=n_batch, verbose=0)
for value in result[0,:]:
    print('%.1f' % value)

Epoch 1/500
 - 0s - loss: 0.1982
Epoch 2/500
 - 0s - loss: 0.1967
Epoch 3/500
 - 0s - loss: 0.1951
Epoch 4/500
 - 0s - loss: 0.1934
Epoch 5/500
 - 0s - loss: 0.1916
Epoch 6/500
 - 0s - loss: 0.1899
Epoch 7/500
 - 0s - loss: 0.1881
Epoch 8/500
 - 0s - loss: 0.1862
Epoch 9/500
 - 0s - loss: 0.1844
Epoch 10/500
 - 0s - loss: 0.1826
Epoch 11/500
 - 0s - loss: 0.1808
Epoch 12/500
 - 0s - loss: 0.1790
Epoch 13/500
 - 0s - loss: 0.1772
Epoch 14/500
 - 0s - loss: 0.1754
Epoch 15/500
 - 0s - loss: 0.1736
Epoch 16/500
 - 0s - loss: 0.1718
Epoch 17/500
 - 0s - loss: 0.1700
Epoch 18/500
 - 0s - loss: 0.1682
Epoch 19/500
 - 0s - loss: 0.1664
Epoch 20/500
 - 0s - loss: 0.1647
Epoch 21/500
 - 0s - loss: 0.1629
Epoch 22/500
 - 0s - loss: 0.1611
Epoch 23/500
 - 0s - loss: 0.1594
Epoch 24/500
 - 0s - loss: 0.1576
Epoch 25/500
 - 0s - loss: 0.1558
Epoch 26/500
 - 0s - loss: 0.1541
Epoch 27/500
 - 0s - loss: 0.1523
Epoch 28/500
 - 0s - loss: 0.1506
Epoch 29/500
 - 0s - loss: 0.1489
Epoch 30/500
 - 0s - lo

Epoch 232/500
 - 0s - loss: 5.0675e-06
Epoch 233/500
 - 0s - loss: 4.4694e-06
Epoch 234/500
 - 0s - loss: 3.9365e-06
Epoch 235/500
 - 0s - loss: 3.4616e-06
Epoch 236/500
 - 0s - loss: 3.0395e-06
Epoch 237/500
 - 0s - loss: 2.6647e-06
Epoch 238/500
 - 0s - loss: 2.3316e-06
Epoch 239/500
 - 0s - loss: 2.0376e-06
Epoch 240/500
 - 0s - loss: 1.7776e-06
Epoch 241/500
 - 0s - loss: 1.5483e-06
Epoch 242/500
 - 0s - loss: 1.3458e-06
Epoch 243/500
 - 0s - loss: 1.1681e-06
Epoch 244/500
 - 0s - loss: 1.0120e-06
Epoch 245/500
 - 0s - loss: 8.7528e-07
Epoch 246/500
 - 0s - loss: 7.5568e-07
Epoch 247/500
 - 0s - loss: 6.5115e-07
Epoch 248/500
 - 0s - loss: 5.6019e-07
Epoch 249/500
 - 0s - loss: 4.8079e-07
Epoch 250/500
 - 0s - loss: 4.1194e-07
Epoch 251/500
 - 0s - loss: 3.5242e-07
Epoch 252/500
 - 0s - loss: 3.0095e-07
Epoch 253/500
 - 0s - loss: 2.5660e-07
Epoch 254/500
 - 0s - loss: 2.1834e-07
Epoch 255/500
 - 0s - loss: 1.8563e-07
Epoch 256/500
 - 0s - loss: 1.5759e-07
Epoch 257/500
 - 0s - los

 - 0s - loss: 2.5269e-14
Epoch 443/500
 - 0s - loss: 2.5269e-14
Epoch 444/500
 - 0s - loss: 2.6201e-14
Epoch 445/500
 - 0s - loss: 2.6201e-14
Epoch 446/500
 - 0s - loss: 2.6201e-14
Epoch 447/500
 - 0s - loss: 2.6201e-14
Epoch 448/500
 - 0s - loss: 2.4380e-14
Epoch 449/500
 - 0s - loss: 2.4380e-14
Epoch 450/500
 - 0s - loss: 2.6201e-14
Epoch 451/500
 - 0s - loss: 2.4070e-14
Epoch 452/500
 - 0s - loss: 2.3137e-14
Epoch 453/500
 - 0s - loss: 2.3137e-14
Epoch 454/500
 - 0s - loss: 2.3137e-14
Epoch 455/500
 - 0s - loss: 2.3137e-14
Epoch 456/500
 - 0s - loss: 2.3137e-14
Epoch 457/500
 - 0s - loss: 2.3137e-14
Epoch 458/500
 - 0s - loss: 2.2249e-14
Epoch 459/500
 - 0s - loss: 2.2249e-14
Epoch 460/500
 - 0s - loss: 2.2249e-14
Epoch 461/500
 - 0s - loss: 2.1494e-14
Epoch 462/500
 - 0s - loss: 2.1494e-14
Epoch 463/500
 - 0s - loss: 2.3626e-14
Epoch 464/500
 - 0s - loss: 2.3626e-14
Epoch 465/500
 - 0s - loss: 2.4425e-14
Epoch 466/500
 - 0s - loss: 2.4425e-14
Epoch 467/500
 - 0s - loss: 2.4425e-14


In [15]:
from numpy import array
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import TimeDistributed
from keras.layers import LSTM
# prepare sequence
length = 5
seq = array([i/float(length) for i in range(length)])
X = seq.reshape(1, length, 1)
y = seq.reshape(1, length, 1)

# define LSTM configuration
n_neurons = length
n_batch = 1
n_epoch = 1000

# create LSTM
# model = Sequential()
# model.add(LSTM(n_neurons, input_shape=(length, 1), return_sequences=True))
# model.add(TimeDistributed(Dense(1)))
# model.compile(loss='mean_squared_error', optimizer='adam')
# print(model.summary())

inputs = Input((length, 1))
lstm = LSTM(n_neurons, return_sequences=True)(inputs)
dense = TimeDistributed(Dense(1))(lstm)
model.compile(loss='mean_squared_error', optimizer='adam')
model.summary()


Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_9 (LSTM)                (None, 5, 5)              140       
_________________________________________________________________
time_distributed_2 (TimeDist (None, 5, 1)              6         
Total params: 146
Trainable params: 146
Non-trainable params: 0
_________________________________________________________________


In [16]:
# train LSTM
model.fit(X, y, epochs=n_epoch, batch_size=n_batch, verbose=0)

In [17]:
X

array([[[0. ],
        [0.2],
        [0.4],
        [0.6],
        [0.8]]])

In [18]:
y

array([[[0. ],
        [0.2],
        [0.4],
        [0.6],
        [0.8]]])

In [19]:
# evaluate
result = model.predict(X, batch_size=n_batch, verbose=0)
for value in result[0,:,0]:
    print('%.1f' % value)

0.0
0.2
0.4
0.6
0.8


In [20]:
result

array([[[0.03901962],
        [0.18634596],
        [0.38260686],
        [0.60055745],
        [0.8064077 ]]], dtype=float32)

In [6]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_4 (LSTM)                (None, 5, 5)              140       
_________________________________________________________________
time_distributed_3 (TimeDist (None, 5, 1)              6         
Total params: 146
Trainable params: 146
Non-trainable params: 0
_________________________________________________________________
